from fastapi import APIRouter, Body, HTTPException

from app.engine.variant_rules import (
    InvalidFenError,
    InvalidUciMoveError,
    IllegalMoveError,
    apply_move,
    board_from_fen,
    create_new_game,
    serialize_board_state,
)
from app.schemas.game import (
    GameMoveRequest,
    GameStateResponse,
    LastMove,
    LegalMovesRequest,
    LegalMovesResponse,
    MoveHistoryEntry,
    NewGameRequest,
)

router = APIRouter()


@router.post("/new", response_model=GameStateResponse)
def new_game(
    request: NewGameRequest = Body(default_factory=NewGameRequest),
) -> GameStateResponse:
    board = create_new_game()
    return _game_state_response(
        board=board,
        message="New Antichess game created.",
        player_color=request.player_color,
        bot_type=request.bot_type,
    )


@router.post("/legal-moves", response_model=LegalMovesResponse)
def legal_moves(
    request: LegalMovesRequest = Body(default_factory=LegalMovesRequest),
) -> LegalMovesResponse:
    try:
        board = board_from_fen(request.fen) if request.fen else create_new_game()
    except InvalidFenError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    state = serialize_board_state(board)
    return LegalMovesResponse(
        game_id=request.game_id or "antichess-local",
        message="Real Antichess legal moves generated by python-chess.",
        **state.model_dump(),
    )


@router.post("/move", response_model=GameStateResponse)
def make_move(request: GameMoveRequest) -> GameStateResponse:
    uci_move = request.move_uci()
    if not uci_move:
        raise HTTPException(
            status_code=400,
            detail="uci_move is required and must be valid UCI notation.",
        )

    try:
        board, last_move = apply_move(request.fen, uci_move)
    except (InvalidFenError, InvalidUciMoveError, IllegalMoveError) as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    return _game_state_response(
        board=board,
        message="Move applied under Antichess rules.",
        player_color=request.player_color,
        bot_type=request.bot_type,
        last_move=last_move,
    )


def _game_state_response(
    *,
    board,
    message: str,
    player_color: str,
    bot_type: str,
    last_move: LastMove | None = None,
) -> GameStateResponse:
    state = serialize_board_state(board)
    return GameStateResponse(
        game_id="antichess-local",
        variant="Giveaway / Antichess",
        status="game_over" if state.game_over else "active",
        message=message,
        side_to_move=state.turn,
        player_color=player_color,
        bot_type=bot_type,
        move_history=_move_history_from_last_move(
            last_move,
            state.turn,
            board.fullmove_number,
        ),
        last_move=last_move,
        candidate_moves=[],
        **state.model_dump(),
    )


def _move_history_from_last_move(
    last_move: LastMove | None,
    next_turn: str,
    fullmove_number: int,
) -> list[MoveHistoryEntry]:
    if last_move is None:
        return []

    last_move_was_white = next_turn == "black"
    turn_number = (
        fullmove_number if last_move_was_white else max(1, fullmove_number - 1)
    )
    return [
        MoveHistoryEntry(
            turn=turn_number,
            white=last_move.san if last_move_was_white else None,
            black=last_move.san if not last_move_was_white else None,
        )
    ]
